profile        = "default"
vendor_name    = "tikal"
region         = "us-west-2"
primary_domain = "tikal.io"
env            = "tf-customer1"
bucket         = "aaltopiiri-terraform-bucket"
dynamodb_table = "aws-locks"